name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Create vim directory
        run: mkdir -p $HOME/.vim

      - uses: actions/checkout@v4

      - name: Copy repository to vim directory
        run: |
          cp -r . $HOME/.vim/vim-scratch-buffer/
          ls -la $HOME/.vim/vim-scratch-buffer/

      - uses: rhysd/action-setup-vim@v1

      - name: Clone themis
        run: git clone https://github.com/thinca/vim-themis $HOME/.vim/bundle/vim-themis

      - name: Run test
        run: $HOME/.vim/bundle/vim-themis/bin/themis $HOME/.vim/vim-scratch-buffer/test --reporter spec
