name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
        path: ~/.vim/vim-scratch-buffer

      - uses: rhysd/action-setup-vim@v1

      - name: Clone themis
        run: git clone https://github.com/thinca/vim-themis ~/.vim/bundle/vim-themis

      - name: Run test
        run: ~/.vim/bundle/vim-themis/bin/themis ~/.vim/vim-scratch-buffer/test --reporter spec
